<h4
    >Matrix product


Problem 1
Matrix product is calculated manually<h4>
    
For matrix multiplication, the number of columns in the first matrix must be equal to the number of rows in the second matrix. The resulting matrix, known as the matrix product, has the number of rows of the first and the number of columns of the second matrix.
    
 $c_{11} = -1 * 0 +2 * 0+ 3 *2 = 6$
    
 ....................
    
  $c_{33} = 7 x 1 + 8 x (-8) + (-9) x (-1) = -48 $

In [5]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
result= np.zeros((3,3))

for x in range(a_ndarray.shape[0]):
    for y in range(a_ndarray.shape[1]):
        for z in range(b_ndarray.shape[1]):  
            result[x][y] += a_ndarray[x][z] *  b_ndarray[z][y]
    
print(result)



[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


Problem 2  Calculation by NumPy function

In [8]:
result = np.matmul(a_ndarray,b_ndarray)
print("Matmul example",result)

result = np.dot(a_ndarray,b_ndarray)
print("Dot example",result)


Matmul example [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Matmul example [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


Problem 3 Implementation of calculation of a certain element

In [43]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

def multiply_matrix(a_ndarray,b_ndarray):
    result= np.zeros((a_ndarray.shape[0],b_ndarray.shape[0]))
    for x in range(a_ndarray.shape[0]):
        for y in range(a_ndarray.shape[1]):
            for z in range(b_ndarray.shape[1]):  
                result[x][y] += a_ndarray[x][z] *  b_ndarray[z][y]
    
    return result
    
print(multiply_matrix(a_ndarray,b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


Problem 4 Creating a function that performs matrix multiplication

In [44]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

def multiply_matrix(a_ndarray,b_ndarray):
    result= np.zeros((a_ndarray.shape[0],b_ndarray.shape[0]))
    for x in range(a_ndarray.shape[0]):
        for y in range(a_ndarray.shape[1]):
            for z in range(b_ndarray.shape[1]):  
                result[x][y] += a_ndarray[x][z] *  b_ndarray[z][y]
    
    return result
    
print(multiply_matrix(a_ndarray,b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


Problem 5 Judge the input whose calculation is not defined

In [78]:
import numpy as np

def mul_matrices(a_ndarray, b_ndarray):
    result = np.array([[0, 0, 0], [0, 0, 0]])
    for x in range(len(a_ndarray)):
        for y in range(len(b_ndarray[0])):
            for z in range(len(b_ndarray)):
                result[x][y] += a_ndarray[x][z] * b_ndarray[z][y]
    return result

d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

print( mul_matrices(d_ndarray_, e_ndarray))


[[ 21 -18   1]
 [-66  57   8]]


Problem 6 Transposition

In [77]:
def multiply_matrix(a_ndarray,b_ndarray):
    result= np.zeros((a_ndarray.shape[0],b_ndarray.shape[0]))
  
    for x in range(len(a_ndarray)):
        for y in range(len(b_ndarray[0])):
            for z in range(len(b_ndarray)):  
                result[x][y] += a_ndarray[x][z] *  b_ndarray[z][y]
   
    return result

d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
edarray = np.transpose(e_ndarray)
print(edarray)
print(multiply_matrix(d_ndarray_,edarray))

[[-9  6]
 [ 8 -5]
 [ 7  4]]
[[ 46.  -4.   0.]
 [-34.  73.   0.]]
